Added LinearSG species
dmorse/simpatico pull request #48
Opened 2018-02-23 23:30 UTC by jmysona

2018-02-24 16:41 UTC, dmorse commented on src/mcMd/species/LinearSG.cpp
> +      #ifdef INTER_ANGLE
Need to read hasAngles_ bool variable to specify whether the molecule has an angle 
potential or not. If hasAngles_, it need to read an angleType_ integer. See HomopolymerS
as a model.

2018-02-24 16:42 UTC, dmorse commented on src/mcMd/species/LinearSG.cpp
> +      if (nAtom_ > 3)
Need to read hasDihedrals_ and (if hasDihedrals) dihedralType_, as in HomopolymerS class.

2018-02-24 16:46 UTC, dmorse commented on src/mcMd/species/LinearSG.cpp
> +   #ifdef INTER_ANGLE
Change all occurrences of INTER_ANGLE, INTER_DIHEDRAL, INTER_NOPAIR, etc. to 
SIMP_ANGLE, SIMP_DIHEDRAL, SIMP_NOPAIR, etc. Note that the preprocessor macro
names changed to reflect a change in the name of the namespace from to Simp.  This
is why the compiler can't find the functions calculateAngleTypeId and dihedralTypeId.

2018-02-24 16:47 UTC, dmorse commented on src/mcMd/species/LinearSG.cpp
> +   #ifdef INTER_DIHEDRAL
INTER_DIHEDRAL -> SIMP_DIHEDRAL.

The function should return dihedralTypeId_

2018-02-24 16:55 UTC, dmorse commented on src/mcMd/species/LinearSG.cpp
> +   /*
The current Species interface doesn't have any functions to generate random molecules. There is 
instead a separate Generator base class. Subclasses of generators are created by a GeneratorFactory,
that (for now) will instantiate a LinearGenerator for any subclass of Linear.  The only two Generator
subclasses that know exist are a PointGenerator and a LinearGenerator.

2018-02-24 16:57 UTC, dmorse commented on src/mcMd/species/LinearSG.cpp
> +   /*
Sorry, I now see that these are commented out. Please remove commented out function declarations (in header) and definitions (here)

2018-02-24 16:59 UTC, dmorse requested changes
The main required changes are:
1) Mimic treatment of angles and dihedrals in HomopolymerSG, particularly in readSpeciesParam
2) Change INTER_ANGLE etc. macros to SIMP_ANGLE etc. 
3) Remove commented out generation functions

2018-02-24 17:01 UTC, dmorse commented
Josh - I knew there was a problem because the automatic tests failed. The automatic tests are run with angles, dihedrals and external potentials enabled (-a1 -d1 -e1) so make sure you test with same flags.

2018-03-06 01:20 UTC, jmysona commented
Dave,

I made the changes as requested. The code has passed the tests performed by
travis and restarts properly.

--Josh

On Sat, Feb 24, 2018 at 11:01 AM, David Morse <notifications@github.com>
wrote:

> Josh - I knew there was a problem because the automatic tests failed. The
> automatic tests are run with angles, dihedrals and external potentials
> enabled (-a1 -d1 -e1) so make sure you test with same flags.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dmorse/simpatico/pull/48#issuecomment-368242536>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AIEb6oGdPyyZhnMZBMsVf_dlPoW7K-xGks5tYEB3gaJpZM4SRnp5>
> .
>

2018-03-06 02:44 UTC, merged

2018-03-06 02:55 UTC, dmorse commented
Josh, 
     I merged the pull request, because nothing appeared wrong, but didn't
understand why you chose to implement this function this way:

 void LinearSG::setMoleculeState(Molecule& molecule, int stateId)
  {
       int nAtom  = molecule.nAtom();
       DArray<int> beadIdentities;
       for (int i = 0; i < nAtom; ++i) {
          if (stateId == 0) {
             beadIdentities = beadTypeIds0_;
          } else {
             beadIdentities = beadTypeIds1_;
          }
          molecule.atom(i).setTypeId(beadIdentities[i]);
       }
       setMoleculeStateId(molecule, stateId);
  }

Questions:
   1) Why repeatedly make a copy of an entire array inside a loop over atoms, rather 
       than copying the array before entering the loop? 
   2) Why make a temporary local copy of the entire appropriate beadTypeIds_ array 
       at all? All you need to do is assign appropriate values to atom type Ids. Why not
      just:

       int typeId
       for (int i = 0; i < nAtom; ++i) {
            if (stateId == 0) {
                typeId = beadTypeIds0_[i];
            } else {
                typeId = beadTypeIds1_[i];
           }
           molecule.atom(i).setTypeId(beadTypeId);
      }

      If you agree, please change and send another tiny pull request.

2018-03-07 04:37 UTC, jmysona commented
That's a very good point. The repeated copying of the array is excessive. I
think the original intention was to avoid having to evaluate an if
statement multiple times.

Currently I've gone with a third option which avoids the repeated
evaluation of the if statement; the code checks to see which subtype it
should set the molecule to, then loops over the atoms assigning them their
new types. The code is now

      int nAtom  = molecule.nAtom();
      if (stateId == 0) {
        for (int i = 0; i < nAtom; ++i) {
          molecule.atom(i).setTypeId(beadTypeIds0_[i]);
        }
      } else {
        for (int i = 0; i < nAtom; ++i) {
          molecule.atom(i).setTypeId(beadTypeIds1_[i]);
        }
      }
      setMoleculeStateId(molecule, stateId);

Let me know if this is acceptable


On Mon, Mar 5, 2018 at 8:55 PM, David Morse <notifications@github.com>
wrote:

> Josh,
> I merged the pull request, because nothing appeared wrong, but didn't
> understand why you chose to implement this function this way:
>
> void LinearSG::setMoleculeState(Molecule& molecule, int stateId)
> {
> int nAtom = molecule.nAtom();
> DArray beadIdentities;
> for (int i = 0; i < nAtom; ++i) {
> if (stateId == 0) {
> beadIdentities = beadTypeIds0_;
> } else {
> beadIdentities = beadTypeIds1_;
> }
> molecule.atom(i).setTypeId(beadIdentities[i]);
> }
> setMoleculeStateId(molecule, stateId);
> }
>
> Questions:
>
>    1.
>
>    Why repeatedly make a copy of an entire array inside a loop over
>    atoms, rather
>    than copying the array before entering the loop?
>    2.
>
>    Why make a temporary local copy of the entire appropriate beadTypeIds_
>    array
>    at all? All you need to do is assign appropriate values to atom type
>    Ids. Why not
>    just:
>
>    int typeId
>    for (int i = 0; i < nAtom; ++i) {
>    if (stateId == 0) {
>    typeId = beadTypeIds0_[i];
>    } else {
>    typeId = beadTypeIds1_[i];
>    }
>    molecule.atom(i).setTypeId(beadTypeId);
>    }
>
>    If you agree, please change and send another tiny pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dmorse/simpatico/pull/48#issuecomment-370644731>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AIEb6pHBHo00CuLPWIwAjHyFG_hXsnRoks5tbfqIgaJpZM4SRnp5>
> .
>

2018-03-07 13:43 UTC, dmorse commented
Josh,
    That looks fine, and its also the most efficient option.
-Dave

On Tue, Mar 6, 2018 at 10:38 PM, jmysona <notifications@github.com> wrote:

> That's a very good point. The repeated copying of the array is excessive. I
> think the original intention was to avoid having to evaluate an if
> statement multiple times.
>
> Currently I've gone with a third option which avoids the repeated
> evaluation of the if statement; the code checks to see which subtype it
> should set the molecule to, then loops over the atoms assigning them their
> new types. The code is now
>
> int nAtom = molecule.nAtom();
> if (stateId == 0) {
> for (int i = 0; i < nAtom; ++i) {
> molecule.atom(i).setTypeId(beadTypeIds0_[i]);
> }
> } else {
> for (int i = 0; i < nAtom; ++i) {
> molecule.atom(i).setTypeId(beadTypeIds1_[i]);
> }
> }
> setMoleculeStateId(molecule, stateId);
>
> Let me know if this is acceptable
>
>
> On Mon, Mar 5, 2018 at 8:55 PM, David Morse <notifications@github.com>
> wrote:
>
> > Josh,
> > I merged the pull request, because nothing appeared wrong, but didn't
> > understand why you chose to implement this function this way:
> >
> > void LinearSG::setMoleculeState(Molecule& molecule, int stateId)
> > {
> > int nAtom = molecule.nAtom();
> > DArray beadIdentities;
> > for (int i = 0; i < nAtom; ++i) {
> > if (stateId == 0) {
> > beadIdentities = beadTypeIds0_;
> > } else {
> > beadIdentities = beadTypeIds1_;
> > }
> > molecule.atom(i).setTypeId(beadIdentities[i]);
> > }
> > setMoleculeStateId(molecule, stateId);
> > }
> >
> > Questions:
> >
> > 1.
> >
> > Why repeatedly make a copy of an entire array inside a loop over
> > atoms, rather
> > than copying the array before entering the loop?
> > 2.
> >
> > Why make a temporary local copy of the entire appropriate beadTypeIds_
> > array
> > at all? All you need to do is assign appropriate values to atom type
> > Ids. Why not
> > just:
> >
> > int typeId
> > for (int i = 0; i < nAtom; ++i) {
> > if (stateId == 0) {
> > typeId = beadTypeIds0_[i];
> > } else {
> > typeId = beadTypeIds1_[i];
> > }
> > molecule.atom(i).setTypeId(beadTypeId);
> > }
> >
> > If you agree, please change and send another tiny pull request.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/dmorse/simpatico/pull/48#issuecomment-370644731>,
> or mute
> > the thread
> > <https://github.com/notifications/unsubscribe-auth/
> AIEb6pHBHo00CuLPWIwAjHyFG_hXsnRoks5tbfqIgaJpZM4SRnp5>
> > .
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/dmorse/simpatico/pull/48#issuecomment-371020343>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABweIDjUNef8hKuhbyPjivJ_X5jQR1-oks5tb2QngaJpZM4SRnp5>
> .
>